### ISSUE TITLE
Ability to connect to instance with API Key instead of master key

### ISSUE THREAD

**Issue by hanyuwei70** [riccox/meilisearch-ui#114]
As title describes, the UI seems only accept master key. I am willing to connect to friend's instance using API key.

**Comment by riccox** [comment]
Because this UI provide some admin features need master key now like key management.
Maybe we can add some additional params in instance config form in the future to control conditional UI routes for common API Key (search/admin).

**Comment by riccox** [comment]
@hanyuwei70 

This issue will be closed due to complexity of implementation.

To control conditional UI routes, the API key should request their own meta data(indexes,actions...) first, then add lots of conditional codes to achieve that.

According to meilisearch official docs, API key which wanna to request their own meta data need to have access to the `keys.get` actions.

This will increase the mental burden of developers.

**Comment by hanyuwei70** [comment]
That's sad, but is ok for me :)

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
