### ISSUE TITLE
More visualization support

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#3]
This is great! 
I hope you can refer to Meilisearch ui adds more functions.

Refer to:  https://github.com/emeagenciadigital/meilisearchadmin

![image](https://user-images.githubusercontent.com/35259040/197341368-8589160c-c37c-4d13-83a6-8d6640719498.png)

**Comment by lrvinye** [comment]
Hi @Avey777 

As far as i known, the meilisearch still in unstable development stage, so that means there would be highly possible to update some config properties in this stage.
and i do not wanna be confused by that kind of things.

The features about the visual operations of config will be added ASAP in the future once the meilisearch released main stable version.

**Comment by Avey777** [comment]
Meilisearch has planned a stable version. This is just to help you better design page interaction styles in the future.

Thank you for your contribution！

**Comment by lrvinye** [comment]
I'll keep an eye on it，thanks 💪

**Comment by Avey777** [comment]
> 我会密切关注的，谢谢肌肉

Meilisearch version 1.0.0 has been released. Is there any plan to add visual configuration?

**Comment by riccox** [comment]
@Avey777 Hi!
I am so exciting to tell you that I have completed this feat in new release version [v0.2.0](https://github.com/riccox/meilisearch-ui/releases/tag/v0.2.0) already.
Hope you will like that.

**Comment by Avey777** [comment]
> @Avey777 Hi! I am so exciting to tell you that I have completed this feat in new release version [v0.2.0](https://github.com/riccox/meilisearch-ui/releases/tag/v0.2.0) already. Hope you will like that.

Thank you very much for your selfless contribution. I watch the update of meilisearch-ui every day. I have started to use it at the first time
