### ISSUE TITLE
Option to disable automatic refreshes

### ISSUE THREAD

**Issue by ahmednfwela** [riccox/meilisearch-ui#42]
**Is your feature request related to a problem? Please describe.**
Connecting to a hosted meilisearch server is costly, so automatic refreshes will increase the cost, especially if you forget the tab open for a long time

**Describe the solution you'd like**
A toggle to enable/disable automatic refreshes

**Comment by riccox** [comment]
Hi @ahmednfwela ,
I decide not to realize the toggle to enable/disable automatic refreshes behavior temporarily because of busy life.
But I have updated some config params to lower the refresh freq in new [release](https://github.com/riccox/meilisearch-ui/releases/tag/v0.4.0), wish that could make u love it.
And I have add the toggle feature you mentioned to my todo list.
You will see it soon 💪.

**Comment by ahmednfwela** [comment]
Thank you very much! this is the best dashboard available right now for meilisearch, really appreciate your effort!

**Comment by riccox** [comment]
@ahmednfwela 


The new version v0.7.1 with auto refresh control has been published. Hope you can try it.
